[package]
name = "gruggers"
version = "0.2.0"
edition = "2024"
authors = ["Nikhil Nathanael Ilango"]
description = "rust implementation of the grug language"
repository = "https://github.com/grug-lang/grug-rs"
license = "MIT"

[dependencies]
json = "0.12.4"
allocator-api2 = "0.4.0"
